<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DriversSeeder extends Seeder
{
    public function run()
    {

        DB::table('drivers')->delete();

        $specialDrivers = [
            [
                "id" => 2,
                "firstName" => "Bassam",
                "lastName" => "Nakkez",
                "officeId" => 1,
                'password' => Hash::make('Aa123456**'),
                "vehicleId" => 1,
                "address" => " ",
                "country" => "سوريا",
                "city" => "دمشق",
                "region" => "maza",
                "isActive" => 1,
                "isConected" => false,
                "gender" => "male",
                "phoneNumber" => "933817392",
                "car_owner" => 0,
                "free_driver" => 0,
                "walletBalance" => 916515,
                "officeDues" => 0,
                "fleetDues" => 0,
                "kmCount" => 0,
                "rideCount" => 0,
                "rating" => 3.1678222839782,
                "photo" => "\storage\images\system\user_no_photo4a305405-ad0b-473a-a40c-456397a18b96.png",
                "ratingExcellent" => 0,
                "ratingGood" => 0,
                "ratingAverage" => 0,
                "ratingBelowAverage" => 0,
                "ratingPoor" => 0,
                "deleted_at" => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id" => 5,
                "firstName" => "0933444222",
                "lastName" => "Driver1",
                'password' => Hash::make('Aa123456**'),
                "officeId" => 1,
                "vehicleId" => 1,
                "address" => " ",
                "country" => "سوريا",
                "city" => "دمشق",
                "region" => "maza",
                "isActive" => 1,
                "isConected" => true,
                "gender" => "male",
                "phoneNumber" => "933444222",
                "car_owner" => 0,
                "free_driver" => 0,
                "walletBalance" => 75000,
                "officeDues" => 306,
                "fleetDues" => 306,
                "kmCount" => 0,
                "rideCount" => 0,
                "rating" => 2.75,
                "photo" => "\storage\images\system\user_no_photo4a305405-ad0b-473a-a40c-456397a18b96.png",
                "ratingExcellent" => 0,
                "ratingGood" => 0,
                "ratingAverage" => 0,
                "ratingBelowAverage" => 0,
                "ratingPoor" => 0,
                "deleted_at" => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id" => 6,
                "firstName" => "Driver2",
                "lastName" => "Driver2",
                'password' => Hash::make('Aa123456**'),
                "officeId" => 1,
                "vehicleId" => 1,
                "address" => " ",
                "country" => "سوريا",
                "city" => "دمشق",
                "region" => "maza",
                "isActive" => 1,
                "isConected" => false,
                "gender" => "male",
                "phoneNumber" => "933111333",
                "car_owner" => 0,
                "free_driver" => 0,
                "walletBalance" => 75000,
                "officeDues" => 0,
                "fleetDues" => 0,
                "kmCount" => 0,
                "rideCount" => 0,
                "rating" => 0,
                "photo" => "\storage\images\system\user_no_photo4a305405-ad0b-473a-a40c-456397a18b96.png",
                "ratingExcellent" => 0,
                "ratingGood" => 0,
                "ratingAverage" => 0,
                "ratingBelowAverage" => 0,
                "ratingPoor" => 0,
                "deleted_at" => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id" => 7,
                "firstName" => "mo",
                "lastName" => "waga",
                'password' => Hash::make('Aa123456**'),
                "officeId" => 1,
                "vehicleId" => 1,
                "address" => " ",
                "country" => "سوريا",
                "city" => "دمشق",
                "region" => "damascus",
                "isActive" => 1,
                "isConected" => false,
                "gender" => "male",
                "phoneNumber" => "933884491",
                "car_owner" => 0,
                "free_driver" => 0,
                "walletBalance" => 9970286853,
                "officeDues" => 0,
                "fleetDues" => 0,
                "kmCount" => 0,
                "rideCount" => 0,
                "rating" => 3.0019454061985,
                "photo" => "/storage/user/profile/d86b222c-7405-4fb5-9e91-7d35d02d1aa8.jpg",
                "ratingExcellent" => 0,
                "ratingGood" => 0,
                "ratingAverage" => 0,
                "ratingBelowAverage" => 0,
                "ratingPoor" => 0,
                "deleted_at" => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id" => 8,
                "firstName" => "abdullah",
                "lastName" => "ramo",
                'password' => Hash::make('Aa123456**'),
                "officeId" => 1,
                "vehicleId" => 1,
                "address" => " ",
                "country" => "سوريا",
                "city" => "دمشق",
                "region" => "KafarSousah",
                "isActive" => 1,
                "isConected" => true,
                "gender" => "male",
                "phoneNumber" => "586000926",
                "car_owner" => 0,
                "free_driver" => 0,
                "walletBalance" => 0,
                "officeDues" => 0,
                "fleetDues" => 0,
                "kmCount" => 0,
                "rideCount" => 0,
                "rating" => 0,
                "photo" => "/storage/user/profile/99969921-4887-455a-93e5-e98fe55ffa7e.jpg",
                "ratingExcellent" => 0,
                "ratingGood" => 0,
                "ratingAverage" => 0,
                "ratingBelowAverage" => 0,
                "ratingPoor" => 0,
                "deleted_at" => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "id" => 9,
                "firstName" => "Mousab",
                "lastName" => "Alsyoufi",
                'password' => Hash::make('Aa123456**'),
                "officeId" => 1,
                "vehicleId" => 1,
                "address" => " ",
                "country" => "سوريا",
                "city" => "دمشق",
                "region" => "KafarSousah",
                "isActive" => 1,
                "isConected" => false,
                "gender" => "male",
                "phoneNumber" => "933111396",
                "car_owner" => 0,
                "free_driver" => 0,
                "walletBalance" => 134297,
                "officeDues" => 0,
                "fleetDues" => 0,
                "kmCount" => 0,
                "rideCount" => 0,
                "rating" => 3.0151062011719,
                "photo" => "/storage/user/profile/7d7c478c-95cb-4482-8a3e-d1c12adde7ed.jpg",
                "ratingExcellent" => 0,
                "ratingGood" => 0,
                "ratingAverage" => 0,
                "ratingBelowAverage" => 0,
                "ratingPoor" => 0,
                "deleted_at" => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];
        
        DB::table('drivers')->insert($specialDrivers);
        
        $names = [
            ['Ahmed', 'Ali'], 
            ['Mohammed', 'Saleh'], 
            ['Hassan', 'Omar'],
            ['Abdullah', 'Yousef'], 
            ['Khalid', 'Nasser'], 
            ['Bilal', 'Ibrahim'],
            ['Sami', 'Hamad'], 
            ['Majed', 'Adel'], 
            ['Tariq', 'Hatem'],
            ['Rami', 'Fadi'], 
            ['Said', 'Mustafa'], 
            ['Imran', 'Farid'],
            ['Yasin', 'Wael'], 
            ['Nabil', 'Mansour'], 
            ['Anwar', 'Kareem'],
            ['Fahad', 'Saad'],
            ['Othman', 'Rashid'],
            ['Jamal', 'Mahmoud'],
            ['Adnan', 'Salim'],
            ['Ziad', 'Tamer'],
            ['Laith', 'Bassam'],
            ['Omar', 'Hazem'],
            ['Ayman', 'Raed'],
            ['Sherif', 'Khalil'],
        ];
        
        $drivers = [];
        $i= 0;
        $id = 10;
        foreach ($names as $index => $name) {
            $i++;
            $id++;
            $drivers[] = [
                'id'=>$id,
                'firstName' => $name[0],
                'lastName' => $name[1],
                'officeId' => rand(0, 5) === 0 ? null : rand(1, 5),
                'password' => Hash::make('Aa123456**'),
                'vehicleId' =>  $i,
                'address' => 'Deira - Dubai , UAE',
                'country' => 'سوريا',
                'city' => 'دمشق',
                'region' => 'maza',
                'isActive' => 1,
                'isConected' => rand(0, 1),
                'gender' => 'male',
                'phoneNumber' => '9' . rand(10000000, 99999999),
                'car_owner' => rand(0, 1),
                'free_driver' => 0,
                'walletBalance' => rand(150000, 263000),
                'officeDues' => rand(0, 1000),
                'fleetDues' => rand(0, 1000),
                'kmCount' => 0,
                'rideCount' => 0,
                'rating' => rand(0, 40)/10,
                'photo' => 'storage\\profile-images\\driver\\' . ($index + 1) . '.png',
                'ratingExcellent' => 0,
                'ratingGood' => 0,
                'ratingAverage' => 0,
                'ratingBelowAverage' => 0,
                'ratingPoor' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('drivers')->insert($drivers);
    }
}
