<?php

namespace Database\Seeders;

use App\Http\Core\Const\Options\Roles;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Employee;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    public function run()
    {
        DB::table('employees')->delete();


        $employees = [
            // --- man ---
            [
                'firstName' => 'Mohammad',
                'lastName' => 'AlWagha',
                'email' => 'mohammad.alwagha@fleet.plus',
                'phoneNumber' => '971501112233',
                'employeeJobName_en' => 'Call Center Agent',
                'employeeJobName_ar' => 'وكيل مركز الاتصال',
                'job_description_en' => 'Handles customer calls and bookings',
                'job_description_ar' => 'يتعامل مع مكالمات العملاء والحجوزات',
                'officeId' => 1,
                'address' => 'Building 12, Street 45, Business Bay, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Business Bay',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m1.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Ali',
                'lastName' => 'Hassan',
                'email' => 'ali.hassan@fleet.plus',
                'phoneNumber' => '971502223344',
                'employeeJobName_en' => 'Driver Support',
                'employeeJobName_ar' => 'دعم السائقين',
                'job_description_en' => 'Handles driver app issues and guidance',
                'job_description_ar' => 'يتعامل مع مشاكل تطبيق السائق والإرشادات',
                'officeId' => 5,
                'address' => 'Apartment 101, Marina Heights, Dubai Marina, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Marina',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m2.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Omar',
                'lastName' => 'AlSayegh',
                'email' => 'omar.alsayegh@fleet.plus',
                'phoneNumber' => '971503334455',
                'employeeJobName_en' => 'Technical Support',
                'employeeJobName_ar' => 'الدعم الفني',
                'job_description_en' => 'Handles technical issues for offices',
                'job_description_ar' => 'يتعامل مع المشاكل الفنية للمكاتب',
                'officeId' => null,
                'address' => 'Office 12, Tech Park, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Tech Park',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m3.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Khalid',
                'lastName' => 'AlAmri',
                'email' => 'khalid.alamri@fleet.plus',
                'phoneNumber' => '971504445566',
                'employeeJobName_en' => 'Operations Manager',
                'employeeJobName_ar' => 'مدير العمليات',
                'job_description_en' => 'Supervises trips and daily operations',
                'job_description_ar' => 'يشرف على الرحلات والعمليات اليومية',
                'officeId' => 4,
                'address' => 'Villa 23, Al Quoz Industrial Area, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'admin',
                'city' => 'Dubai',
                'region' => 'Al Quoz',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m4.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Youssef',
                'lastName' => 'AlNuaimi',
                'email' => 'youssef.alnuaimi@fleet.plus',
                'phoneNumber' => '971505556677',
                'employeeJobName_en' => 'Fleet Supervisor',
                'employeeJobName_ar' => 'مشرف الأسطول',
                'job_description_en' => 'Manages fleet allocation and maintenance',
                'job_description_ar' => 'يدير تخصيص الأسطول والصيانة',
                'officeId' => 1,
                'address' => 'Street 15, Al Barsha, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'admin',
                'city' => 'Dubai',
                'region' => 'Al Barsha',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m5.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Fahad',
                'lastName' => 'AlKhaldi',
                'email' => 'fahad.alkhaldi@fleet.plus',
                'phoneNumber' => '971506667788',
                'employeeJobName_en' => 'Trip Coordinator',
                'employeeJobName_ar' => 'منسق الرحلات',
                'job_description_en' => 'Coordinates trips between drivers and clients',
                'job_description_ar' => 'ينسق الرحلات بين السائقين والعملاء',
                'officeId' => 2,
                'address' => 'Tower 5, Jumeirah Lake Towers, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'JLT',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m6.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Saud',
                'lastName' => 'AlHarbi',
                'email' => 'saud.alharbi@fleet.plus',
                'phoneNumber' => '971507778899',
                'employeeJobName_en' => 'System Analyst',
                'employeeJobName_ar' => 'محلل النظام',
                'job_description_en' => 'Analyzes app performance and issues',
                'job_description_ar' => 'يحلل أداء التطبيق والمشاكل',
                'officeId' => 5,
                'address' => 'Apartment 303, Dubai Silicon Oasis, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'viewer',
                'city' => 'Dubai',
                'region' => 'DSO',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m7.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Abdullah',
                'lastName' => 'AlShamsi',
                'email' => 'abdullah.alshamsi@fleet.plus',
                'phoneNumber' => '971508889900',
                'employeeJobName_en' => 'App Tester',
                'employeeJobName_ar' => 'مختبر التطبيق',
                'job_description_en' => 'Tests new features and reports bugs',
                'job_description_ar' => 'يختبر الميزات الجديدة ويبلغ عن الأخطاء',
                'officeId' => null,
                'address' => 'Villa 12, Al Safa, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Al Safa',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m8.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Hamad',
                'lastName' => 'AlOtaibi',
                'email' => 'hamad.alotaibi@fleet.plus',
                'phoneNumber' => '971509990011',
                'employeeJobName_en' => 'Route Planner',
                'employeeJobName_ar' => 'مخطط المسارات',
                'job_description_en' => 'Plans optimal routes for drivers',
                'job_description_ar' => 'يخطط المسارات المثلى للسائقين',
                'officeId' => 5,
                'address' => 'Office 7, Dubai Internet City, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'admin',
                'city' => 'Dubai',
                'region' => 'DIC',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m9.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Majed',
                'lastName' => 'AlRashid',
                'email' => 'majed.alrashid@fleet.plus',
                'phoneNumber' => '971501001122',
                'employeeJobName_en' => 'Admin Supervisor',
                'employeeJobName_ar' => 'مشرف الإدارة',
                'job_description_en' => 'Supervises admin tasks and office management',
                'job_description_ar' => 'يشرف على المهام الإدارية وإدارة المكاتب',
                'officeId' => 4,
                'address' => 'Street 11, Al Wasl, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'admin',
                'city' => 'Dubai',
                'region' => 'Al Wasl',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'male',
                'photo' => 'storage/profile-images/emp/m10.png',
                'password' => Hash::make('Aa123456**'),
            ],

            // --- waman ---
            [
                'firstName' => 'Sara',
                'lastName' => 'AlMansoori',
                'email' => 'sara.almansoori@fleet.plus',
                'phoneNumber' => '971502223344',
                'employeeJobName_en' => 'Customer Support',
                'employeeJobName_ar' => 'دعم العملاء',
                'job_description_en' => 'Provides support for user app issues',
                'job_description_ar' => 'يوفر الدعم لمشاكل تطبيق المستخدم',
                'officeId' => 2,
                'address' => 'Villa 8, Street 23, Al Barsha, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Al Barsha',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'female',
                'photo' => 'storage/profile-images/emp/f1.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Fatima',
                'lastName' => 'AlFahim',
                'email' => 'fatima.alfahim@fleet.plus',
                'phoneNumber' => '971504445566',
                'employeeJobName_en' => 'Technical Support',
                'employeeJobName_ar' => 'الدعم الفني',
                'job_description_en' => 'Handles technical issues for offices',
                'job_description_ar' => 'يتعامل مع المشاكل الفنية للمكاتب',
                'officeId' => null,
                'address' => 'Office 12, Tech Park, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Tech Park',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'female',
                'photo' => 'storage/profile-images/emp/f2.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Laila',
                'lastName' => 'AlHaddad',
                'email' => 'laila.alhaddad@fleet.plus',
                'phoneNumber' => '971505556677',
                'employeeJobName_en' => 'App Support',
                'employeeJobName_ar' => 'دعم التطبيق',
                'job_description_en' => 'Supports mobile app users and reports issues',
                'job_description_ar' => 'تدعم مستخدمي التطبيق وتبلغ عن المشاكل',
                'officeId' => 4,
                'address' => 'Street 18, Jumeirah, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Jumeirah',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'female',
                'photo' => 'storage/profile-images/emp/f3.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Noura',
                'lastName' => 'AlMazrouei',
                'email' => 'noura.almazrouei@fleet.plus',
                'phoneNumber' => '971506667788',
                'employeeJobName_en' => 'Fleet Coordinator',
                'employeeJobName_ar' => 'منسقة الأسطول',
                'job_description_en' => 'Coordinates fleet operations and scheduling',
                'job_description_ar' => 'تنسق عمليات الأسطول والجدولة',
                'officeId' => 1,
                'address' => 'Apartment 22, Business Bay, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'admin',
                'city' => 'Dubai',
                'region' => 'Business Bay',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'female',
                'photo' => 'storage/profile-images/emp/f4.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Huda',
                'lastName' => 'AlOtaibi',
                'email' => 'huda.alotaibi@fleet.plus',
                'phoneNumber' => '971507778899',
                'employeeJobName_en' => 'Trip Support',
                'employeeJobName_ar' => 'دعم الرحلات',
                'job_description_en' => 'Monitors trip progress and customer feedback',
                'job_description_ar' => 'تتابع تقدم الرحلات وتعليقات العملاء',
                'officeId' => 2,
                'address' => 'Villa 5, Al Safa, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Al Safa',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'female',
                'photo' => 'storage/profile-images/emp/f5.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Amal',
                'lastName' => 'AlSuwaidi',
                'email' => 'amal.alsuwaidi@fleet.plus',
                'phoneNumber' => '971508889900',
                'employeeJobName_en' => 'Admin Assistant',
                'employeeJobName_ar' => 'مساعدة إدارية',
                'job_description_en' => 'Assists admin supervisor in office management',
                'job_description_ar' => 'تساعد المشرف الإداري في إدارة المكتب',
                'officeId' => 5,
                'address' => 'Street 9, Al Barsha, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'agent',
                'city' => 'Dubai',
                'region' => 'Al Barsha',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'female',
                'photo' => 'storage/profile-images/emp/f6.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Maha',
                'lastName' => 'AlQassimi',
                'email' => 'maha.alqassimi@fleet.plus',
                'phoneNumber' => '971509990011',
                'employeeJobName_en' => 'Quality Controller',
                'employeeJobName_ar' => 'مراقبة الجودة',
                'job_description_en' => 'Checks service quality and trip feedback',
                'job_description_ar' => 'تفحص جودة الخدمة وتعليقات الرحلات',
                'officeId' => 3,
                'address' => 'Office 10, Dubai Media City, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'viewer',
                'city' => 'Dubai',
                'region' => 'DMC',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'female',
                'photo' => 'storage/profile-images/emp/f7.png',
                'password' => Hash::make('Aa123456**'),
            ],
            [
                'firstName' => 'Maha',
                'lastName' => 'AlQassimi',
                'email' => 'maha.alqassimi2@fleet.plus',
                'phoneNumber' => '971509990011',
                'employeeJobName_en' => 'Trip Coordinator',
                'employeeJobName_ar' => 'منسق الرحلات',
                'job_description_en' => 'Coordinates trips between drivers and clients',
                'job_description_ar' => 'ينسق الرحلات بين السائقين والعملاء',
                'officeId' => 3,
                'address' => 'Office 10, Dubai Media City, Dubai, UAE',
                'country' => 'UAE',
                'role' => 'viewer',
                'city' => 'Dubai',
                'region' => 'DMC',
                'isActive' => 1,
                'isOnline' => 0,
                'gender' => 'female',
                'photo' => 'storage/profile-images/emp/f8.png',
                'password' => Hash::make('Aa123456**'),
            ],
        ];

        DB::table('employees')->insert($employees);

        $employees = Employee::all();

        foreach($employees as $emp){
        $emp->assignRole(Roles::Employee->value);    
        }
    }
}
