<?php

namespace Database\Seeders;

use App\Http\Core\Const\Options\Roles;
use App\Models\Office;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class OfficesSeeder extends Seeder
{
    public function run()
    {
        DB::table('offices')->delete();

        DB::table('offices')->insert([
            [
                'id'=>1,
                'officeName' => 'Dubai Luxury Fleet',
                'logo' => 'https://st2.depositphotos.com/34474882/46852/v/450/depositphotos_468527452-stock-illustration-mandala-geometric-ornament-logo-elegant.jpg',
                'email' => 'dubailuxury@fleet.plus',
                'password' => Hash::make('Aa123456**'),
                'contactNumber' => '+97144556677',
                'country' => 'UAE',
                'city' => 'Dubai',
                'region' => 'Sheikh Zayed Rd',
                'address' => 'Sheikh Zayed Rd, Dubai, UAE',
                'walletBalance' => 5000,
                'status' => 1,
                'driversDues' => 1200,
                'fleetDues' => 800,
                'commission_with_office_car' => 10,
                'commission_with_driver_car' => 15,
                'driver_commission_precentage' => 80,
                'driver_car_commission_precentage' => 20,
                'officeTypeId' => 1,
                'timeZone' => 'Asia/Dubai',
                'limitOrders' => 50,
                'rating' => 4.9,
                'ratingExcellent' => 40,
                'ratingGood' => 5,
                'ratingAverage' => 3,
                'ratingBelowAverage' => 1,
                'ratingPoor' => 0,
            ],
            [
                'id'=>2,
                'officeName' => 'Golden Travel Taxis',
                'logo' => 'https://images.squarespace-cdn.com/content/v1/64e787bad2cfd34b7a9d4662/fd59c377-84ab-45c6-8903-31097d5edea6/Golden+Travel+Logo.png',
                'email' => 'goldentraveltaxis@fleet.plus',
                'password' => Hash::make('Aa123456**'),
                'contactNumber' => '+97143332211',
                'country' => 'UAE',
                'city' => 'Dubai',
                'region' => 'Deira',
                'address' => 'Al Maktoum Rd, Deira, Dubai, UAE',
                'walletBalance' => 2000,
                'status' => 1,
                'driversDues' => 500,
                'fleetDues' => 300,
                'commission_with_office_car' => 8,
                'commission_with_driver_car' => 12,
                'driver_commission_precentage' => 75,
                'driver_car_commission_precentage' => 15,
                'officeTypeId' => 2,
                'timeZone' => 'Asia/Dubai',
                'limitOrders' => 30,
                'rating' => 4.2,
                'ratingExcellent' => 25,
                'ratingGood' => 10,
                'ratingAverage' => 5,
                'ratingBelowAverage' => 2,
                'ratingPoor' => 1,
            ],
            [
                'id'=>3,
                'officeName' => 'Eco Dubai Transport',
                'logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfa31W5euPiyIZeApYHB7MLRDAJy5cz59OC1szCOHOX2f9h4IF0Q4BShwnD8aPsgoKiz8&usqp=CAU',
                'email' => 'eco@fleet.plus',
                'password' => Hash::make('Aa123456**'),
                'contactNumber' => '+97146668855',
                'country' => 'UAE',
                'city' => 'Dubai',
                'region' => 'Silicon Oasis',
                'address' => 'Dubai Silicon Oasis, Dubai, UAE',
                'walletBalance' => 1500,
                'status' => 1,
                'driversDues' => 300,
                'fleetDues' => 200,
                'commission_with_office_car' => 7,
                'commission_with_driver_car' => 10,
                'driver_commission_precentage' => 70,
                'driver_car_commission_precentage' => 15,
                'officeTypeId' => 3,
                'timeZone' => 'Asia/Dubai',
                'limitOrders' => 20,
                'rating' => 4.7,
                'ratingExcellent' => 30,
                'ratingGood' => 8,
                'ratingAverage' => 4,
                'ratingBelowAverage' => 1,
                'ratingPoor' => 0,
            ],
            [
                'id'=>4,
                'officeName' => 'Metro Fleet Services',
                'logo' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d',
                'email' => 'metrofleet@fleet.plus',
                'password' => Hash::make('Aa123456**'),
                'contactNumber' => '+97145557799',
                'country' => 'UAE',
                'city' => 'Dubai',
                'region' => 'Business Bay',
                'address' => 'Business Bay, Dubai, UAE',
                'walletBalance' => 3000,
                'status' => 1,
                'driversDues' => 800,
                'fleetDues' => 500,
                'commission_with_office_car' => 9,
                'commission_with_driver_car' => 14,
                'driver_commission_precentage' => 78,
                'driver_car_commission_precentage' => 18,
                'officeTypeId' => 1,
                'timeZone' => 'Asia/Dubai',
                'limitOrders' => 40,
                'rating' => 4.5,
                'ratingExcellent' => 35,
                'ratingGood' => 10,
                'ratingAverage' => 5,
                'ratingBelowAverage' => 2,
                'ratingPoor' => 0,
            ],
            [
                'id'=>5,
                'officeName' => 'Palm Chauffeurs',
                'logo' => 'https://images.unsplash.com/photo-1597009545554-3458b8e3e72d',
                'email' => 'palmchauffeurs@fleet.plus',
                'password' => Hash::make('Aa123456**'),
                'contactNumber' => '+97147779933',
                'country' => 'UAE',
                'city' => 'Dubai',
                'region' => 'Palm Jumeirah',
                'address' => 'Palm Jumeirah, Dubai, UAE',
                'walletBalance' => 4000,
                'status' => 1,
                'driversDues' => 1000,
                'fleetDues' => 600,
                'commission_with_office_car' => 10,
                'commission_with_driver_car' => 15,
                'driver_commission_precentage' => 80,
                'driver_car_commission_precentage' => 20,
                'officeTypeId' => 1,
                'timeZone' => 'Asia/Dubai',
                'limitOrders' => 50,
                'rating' => 4.8,
                'ratingExcellent' => 38,
                'ratingGood' => 7,
                'ratingAverage' => 3,
                'ratingBelowAverage' => 1,
                'ratingPoor' => 0,
            ],
        ]);

        $offices = Office::all();

        foreach($offices as $office){
        $office->assignRole(Roles::Office->value);    
        }
    }
}
