<?php

namespace Database\Seeders;

use App\Http\Core\Const\Options\Roles;
use App\Models\Office;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class OfficesSeeder extends Seeder
{
    public function run()
    {
        DB::table('offices')->delete();

        // DB::table('offices')->insert([
        //     [
        //         'id'=>1,
        //         'officeName' => 'Dubai Luxury Fleet',
        //         'logo' => 'https://st2.depositphotos.com/34474882/46852/v/450/depositphotos_468527452-stock-illustration-mandala-geometric-ornament-logo-elegant.jpg',
        //         'email' => 'dubailuxury@fleet.plus',
        //         'password' => Hash::make('Aa123456**'),
        //         'contactNumber' => '+97144556677',
        //         'country' => 'UAE',
        //         'city' => 'Dubai',
        //         'region' => 'Sheikh Zayed Rd',
        //         'address' => 'Sheikh Zayed Rd, Dubai, UAE',
        //         'walletBalance' => 5000,
        //         'status' => 1,
        //         'driversDues' => 1200,
        //         'fleetDues' => 800,
        //         'commission_with_office_car' => 10,
        //         'commission_with_driver_car' => 15,
        //         'driver_commission_precentage' => 80,
        //         'driver_car_commission_precentage' => 20,
        //         'officeTypeId' => 1,
        //         'timeZone' => 'Asia/Dubai',
        //         'limitOrders' => 50,
        //         'rating' => 4.9,
        //         'ratingExcellent' => 40,
        //         'ratingGood' => 5,
        //         'ratingAverage' => 3,
        //         'ratingBelowAverage' => 1,
        //         'ratingPoor' => 0,
        //     ],
        //     [
        //         'id'=>2,
        //         'officeName' => 'Golden Travel Taxis',
        //         'logo' => 'https://images.squarespace-cdn.com/content/v1/64e787bad2cfd34b7a9d4662/fd59c377-84ab-45c6-8903-31097d5edea6/Golden+Travel+Logo.png',
        //         'email' => 'goldentraveltaxis@fleet.plus',
        //         'password' => Hash::make('Aa123456**'),
        //         'contactNumber' => '+97143332211',
        //         'country' => 'UAE',
        //         'city' => 'Dubai',
        //         'region' => 'Deira',
        //         'address' => 'Al Maktoum Rd, Deira, Dubai, UAE',
        //         'walletBalance' => 2000,
        //         'status' => 1,
        //         'driversDues' => 500,
        //         'fleetDues' => 300,
        //         'commission_with_office_car' => 8,
        //         'commission_with_driver_car' => 12,
        //         'driver_commission_precentage' => 75,
        //         'driver_car_commission_precentage' => 15,
        //         'officeTypeId' => 2,
        //         'timeZone' => 'Asia/Dubai',
        //         'limitOrders' => 30,
        //         'rating' => 4.2,
        //         'ratingExcellent' => 25,
        //         'ratingGood' => 10,
        //         'ratingAverage' => 5,
        //         'ratingBelowAverage' => 2,
        //         'ratingPoor' => 1,
        //     ],
        //     [
        //         'id'=>3,
        //         'officeName' => 'Eco Dubai Transport',
        //         'logo' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfa31W5euPiyIZeApYHB7MLRDAJy5cz59OC1szCOHOX2f9h4IF0Q4BShwnD8aPsgoKiz8&usqp=CAU',
        //         'email' => 'eco@fleet.plus',
        //         'password' => Hash::make('Aa123456**'),
        //         'contactNumber' => '+97146668855',
        //         'country' => 'UAE',
        //         'city' => 'Dubai',
        //         'region' => 'Silicon Oasis',
        //         'address' => 'Dubai Silicon Oasis, Dubai, UAE',
        //         'walletBalance' => 1500,
        //         'status' => 1,
        //         'driversDues' => 300,
        //         'fleetDues' => 200,
        //         'commission_with_office_car' => 7,
        //         'commission_with_driver_car' => 10,
        //         'driver_commission_precentage' => 70,
        //         'driver_car_commission_precentage' => 15,
        //         'officeTypeId' => 3,
        //         'timeZone' => 'Asia/Dubai',
        //         'limitOrders' => 20,
        //         'rating' => 4.7,
        //         'ratingExcellent' => 30,
        //         'ratingGood' => 8,
        //         'ratingAverage' => 4,
        //         'ratingBelowAverage' => 1,
        //         'ratingPoor' => 0,
        //     ],
        //     [
        //         'id'=>4,
        //         'officeName' => 'Metro Fleet Services',
        //         'logo' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d',
        //         'email' => 'metrofleet@fleet.plus',
        //         'password' => Hash::make('Aa123456**'),
        //         'contactNumber' => '+97145557799',
        //         'country' => 'UAE',
        //         'city' => 'Dubai',
        //         'region' => 'Business Bay',
        //         'address' => 'Business Bay, Dubai, UAE',
        //         'walletBalance' => 3000,
        //         'status' => 1,
        //         'driversDues' => 800,
        //         'fleetDues' => 500,
        //         'commission_with_office_car' => 9,
        //         'commission_with_driver_car' => 14,
        //         'driver_commission_precentage' => 78,
        //         'driver_car_commission_precentage' => 18,
        //         'officeTypeId' => 1,
        //         'timeZone' => 'Asia/Dubai',
        //         'limitOrders' => 40,
        //         'rating' => 4.5,
        //         'ratingExcellent' => 35,
        //         'ratingGood' => 10,
        //         'ratingAverage' => 5,
        //         'ratingBelowAverage' => 2,
        //         'ratingPoor' => 0,
        //     ],
        //     [
        //         'id'=>5,
        //         'officeName' => 'Palm Chauffeurs',
        //         'logo' => 'https://images.unsplash.com/photo-1597009545554-3458b8e3e72d',
        //         'email' => 'palmchauffeurs@fleet.plus',
        //         'password' => Hash::make('Aa123456**'),
        //         'contactNumber' => '+97147779933',
        //         'country' => 'UAE',
        //         'city' => 'Dubai',
        //         'region' => 'Palm Jumeirah',
        //         'address' => 'Palm Jumeirah, Dubai, UAE',
        //         'walletBalance' => 4000,
        //         'status' => 1,
        //         'driversDues' => 1000,
        //         'fleetDues' => 600,
        //         'commission_with_office_car' => 10,
        //         'commission_with_driver_car' => 15,
        //         'driver_commission_precentage' => 80,
        //         'driver_car_commission_precentage' => 20,
        //         'officeTypeId' => 1,
        //         'timeZone' => 'Asia/Dubai',
        //         'limitOrders' => 50,
        //         'rating' => 4.8,
        //         'ratingExcellent' => 38,
        //         'ratingGood' => 7,
        //         'ratingAverage' => 3,
        //         'ratingBelowAverage' => 1,
        //         'ratingPoor' => 0,
        //     ],
        // ]);


        DB::table('offices')->insert([
    // ----- USA Offices -----

    //     'id'=>1,
    //     'officeName' => 'NYC Luxury Fleet',
    //     'logo' => 'https://example.com/nyc_luxury_logo.png',
    //     'email' => 'nycluxury@fleet.plus',
    //     'password' => Hash::make('Aa123456**'),
    //     'contactNumber' => '+12125550123',
    //     'country' => 'USA',
    //     'city' => 'New York',
    //     'region' => 'Manhattan',
    //     'address' => '123 Manhattan Ave, New York, NY, USA',
    //     'walletBalance' => 6000,
    //     'status' => 1,
    //     'driversDues' => 1500,
    //     'fleetDues' => 1000,
    //     'commission_with_office_car' => 12,
    //     'commission_with_driver_car' => 18,
    //     'driver_commission_precentage' => 80,
    //     'driver_car_commission_precentage' => 20,
    //     'officeTypeId' => 1,
    //     'timeZone' => 'America/New_York',
    //     'limitOrders' => 50,
    //     'rating' => 4.9,
    //     'ratingExcellent' => 40,
    //     'ratingGood' => 5,
    //     'ratingAverage' => 3,
    //     'ratingBelowAverage' => 1,
    //     'ratingPoor' => 0,
    // ],
    // [
    //     'id'=>2,
    //     'officeName' => 'LA Travel Taxis',
    //     'logo' => 'https://example.com/la_travel_logo.png',
    //     'email' => 'latraveltaxis@fleet.plus',
    //     'password' => Hash::make('Aa123456**'),
    //     'contactNumber' => '+13105551234',
    //     'country' => 'USA',
    //     'city' => 'Los Angeles',
    //     'region' => 'Downtown',
    //     'address' => '456 Downtown St, Los Angeles, CA, USA',
    //     'walletBalance' => 4000,
    //     'status' => 1,
    //     'driversDues' => 1200,
    //     'fleetDues' => 700,
    //     'commission_with_office_car' => 10,
    //     'commission_with_driver_car' => 15,
    //     'driver_commission_precentage' => 75,
    //     'driver_car_commission_precentage' => 15,
    //     'officeTypeId' => 2,
    //     'timeZone' => 'America/Los_Angeles',
    //     'limitOrders' => 40,
    //     'rating' => 4.5,
    //     'ratingExcellent' => 35,
    //     'ratingGood' => 8,
    //     'ratingAverage' => 5,
    //     'ratingBelowAverage' => 2,
    //     'ratingPoor' => 0,
    // ],
    // [
    //     'id'=>3,
    //     'officeName' => 'Miami Eco Transport',
    //     'logo' => 'https://example.com/miami_eco_logo.png',
    //     'email' => 'miamieco@fleet.plus',
    //     'password' => Hash::make('Aa123456**'),
    //     'contactNumber' => '+13055556789',
    //     'country' => 'USA',
    //     'city' => 'Miami',
    //     'region' => 'Downtown',
    //     'address' => '789 Ocean Dr, Miami, FL, USA',
    //     'walletBalance' => 3000,
    //     'status' => 1,
    //     'driversDues' => 800,
    //     'fleetDues' => 500,
    //     'commission_with_office_car' => 8,
    //     'commission_with_driver_car' => 12,
    //     'driver_commission_precentage' => 70,
    //     'driver_car_commission_precentage' => 15,
    //     'officeTypeId' => 3,
    //     'timeZone' => 'America/New_York',
    //     'limitOrders' => 30,
    //     'rating' => 4.7,
    //     'ratingExcellent' => 28,
    //     'ratingGood' => 10,
    //     'ratingAverage' => 4,
    //     'ratingBelowAverage' => 1,
    //     'ratingPoor' => 0,
    // ],
    // [
    //     'id'=>4,
    //     'officeName' => 'Chicago Fleet Services',
    //     'logo' => 'https://example.com/chicago_fleet_logo.png',
    //     'email' => 'chicagofleet@fleet.plus',
    //     'password' => Hash::make('Aa123456**'),
    //     'contactNumber' => '+17735551234',
    //     'country' => 'USA',
    //     'city' => 'Chicago',
    //     'region' => 'Loop',
    //     'address' => '101 W Loop, Chicago, IL, USA',
    //     'walletBalance' => 5000,
    //     'status' => 1,
    //     'driversDues' => 1000,
    //     'fleetDues' => 600,
    //     'commission_with_office_car' => 11,
    //     'commission_with_driver_car' => 16,
    //     'driver_commission_precentage' => 78,
    //     'driver_car_commission_precentage' => 18,
    //     'officeTypeId' => 1,
    //     'timeZone' => 'America/Chicago',
    //     'limitOrders' => 45,
    //     'rating' => 4.6,
    //     'ratingExcellent' => 33,
    //     'ratingGood' => 12,
    //     'ratingAverage' => 5,
    //     'ratingBelowAverage' => 2,
    //     'ratingPoor' => 0,
    // ],
    // [
    //     'id'=>5,
    //     'officeName' => 'San Francisco Chauffeurs',
    //     'logo' => 'https://example.com/sf_chauffeurs_logo.png',
    //     'email' => 'sfchauffeurs@fleet.plus',
    //     'password' => Hash::make('Aa123456**'),
    //     'contactNumber' => '+14155551234',
    //     'country' => 'USA',
    //     'city' => 'San Francisco',
    //     'region' => 'Financial District',
    //     'address' => '202 Market St, San Francisco, CA, USA',
    //     'walletBalance' => 4500,
    //     'status' => 1,
    //     'driversDues' => 900,
    //     'fleetDues' => 550,
    //     'commission_with_office_car' => 10,
    //     'commission_with_driver_car' => 15,
    //     'driver_commission_precentage' => 80,
    //     'driver_car_commission_precentage' => 20,
    //     'officeTypeId' => 1,
    //     'timeZone' => 'America/Los_Angeles',
    //     'limitOrders' => 50,
    //     'rating' => 4.8,
    //     'ratingExcellent' => 36,
    //     'ratingGood' => 8,
    //     'ratingAverage' => 3,
    //     'ratingBelowAverage' => 1,
    //     'ratingPoor' => 0,
    // ],

    // ----- Qatar Offices -----
    [
        'id'=>1,
        'officeName' => 'Doha Luxury Fleet',
        'logo' => 'https://example.com/doha_luxury_logo.png',
        'email' => 'dohaluxury@fleet.plus',
        'password' => Hash::make('Aa123456**'),
        'contactNumber' => '+97444556677',
        'country' => 'QATAR',
        'city' => 'Doha',
        'region' => 'West Bay',
        'address' => 'West Bay, Doha, Qatar',
        'walletBalance' => 5500,
        'status' => 1,
        'driversDues' => 1300,
        'fleetDues' => 900,
        'commission_with_office_car' => 12,
        'commission_with_driver_car' => 18,
        'driver_commission_precentage' => 80,
        'driver_car_commission_precentage' => 20,
        'officeTypeId' => 1,
        'timeZone' => 'Asia/Qatar',
        'limitOrders' => 50,
        'rating' => 4.9,
        'ratingExcellent' => 40,
        'ratingGood' => 5,
        'ratingAverage' => 3,
        'ratingBelowAverage' => 1,
        'ratingPoor' => 0,
    ],
    [
        'id'=>2,
        'officeName' => 'Qatar Travel Taxis',
        'logo' => 'https://example.com/qatar_travel_logo.png',
        'email' => 'qatartraveltaxis@fleet.plus',
        'password' => Hash::make('Aa123456**'),
        'contactNumber' => '+97443332211',
        'country' => 'QATAR',
        'city' => 'Doha',
        'region' => 'Al Sadd',
        'address' => 'Al Sadd, Doha, Qatar',
        'walletBalance' => 4000,
        'status' => 1,
        'driversDues' => 1100,
        'fleetDues' => 700,
        'commission_with_office_car' => 10,
        'commission_with_driver_car' => 15,
        'driver_commission_precentage' => 75,
        'driver_car_commission_precentage' => 15,
        'officeTypeId' => 2,
        'timeZone' => 'Asia/Qatar',
        'limitOrders' => 40,
        'rating' => 4.5,
        'ratingExcellent' => 35,
        'ratingGood' => 8,
        'ratingAverage' => 5,
        'ratingBelowAverage' => 2,
        'ratingPoor' => 0,
    ],
    [
        'id'=>3,
        'officeName' => 'Eco Doha Transport',
        'logo' => 'https://example.com/eco_doha_logo.png',
        'email' => 'ecodoha@fleet.plus',
        'password' => Hash::make('Aa123456**'),
        'contactNumber' => '+97446668855',
        'country' => 'QATAR',
        'city' => 'Doha',
        'region' => 'The Pearl',
        'address' => 'The Pearl, Doha, Qatar',
        'walletBalance' => 3500,
        'status' => 1,
        'driversDues' => 900,
        'fleetDues' => 600,
        'commission_with_office_car' => 8,
        'commission_with_driver_car' => 12,
        'driver_commission_precentage' => 70,
        'driver_car_commission_precentage' => 15,
        'officeTypeId' => 3,
        'timeZone' => 'Asia/Qatar',
        'limitOrders' => 30,
        'rating' => 4.7,
        'ratingExcellent' => 28,
        'ratingGood' => 10,
        'ratingAverage' => 4,
        'ratingBelowAverage' => 1,
        'ratingPoor' => 0,
    ],
    [
        'id'=>4,
        'officeName' => 'Doha Fleet Services',
        'logo' => 'https://example.com/doha_fleet_logo.png',
        'email' => 'dohafleet@fleet.plus',
        'password' => Hash::make('Aa123456**'),
        'contactNumber' => '+97445557799',
        'country' => 'QATAR',
        'city' => 'Doha',
        'region' => 'West Bay Lagoon',
        'address' => 'West Bay Lagoon, Doha, Qatar',
        'walletBalance' => 5000,
        'status' => 1,
        'driversDues' => 1200,
        'fleetDues' => 800,
        'commission_with_office_car' => 10,
        'commission_with_driver_car' => 15,
        'driver_commission_precentage' => 78,
        'driver_car_commission_precentage' => 18,
        'officeTypeId' => 1,
        'timeZone' => 'Asia/Qatar',
        'limitOrders' => 45,
        'rating' => 4.6,
        'ratingExcellent' => 33,
        'ratingGood' => 12,
        'ratingAverage' => 5,
        'ratingBelowAverage' => 2,
        'ratingPoor' => 0,
    ],
    [
        'id'=>5,
        'officeName' => 'Pearl Chauffeurs',
        'logo' => 'https://example.com/pearl_chauffeurs_logo.png',
        'email' => 'pearlchauffeurs@fleet.plus',
        'password' => Hash::make('Aa123456**'),
        'contactNumber' => '+97447779933',
        'country' => 'QATAR',
        'city' => 'Doha',
        'region' => 'Pearl Island',
        'address' => 'Pearl Island, Doha, Qatar',
        'walletBalance' => 4500,
        'status' => 1,
        'driversDues' => 1000,
        'fleetDues' => 600,
        'commission_with_office_car' => 10,
        'commission_with_driver_car' => 15,
        'driver_commission_precentage' => 80,
        'driver_car_commission_precentage' => 20,
        'officeTypeId' => 1,
        'timeZone' => 'Asia/Qatar',
        'limitOrders' => 50,
        'rating' => 4.8,
        'ratingExcellent' => 36,
        'ratingGood' => 8,
        'ratingAverage' => 3,
        'ratingBelowAverage' => 1,
        'ratingPoor' => 0,
    ],
]);

        $offices = Office::all();

        foreach($offices as $office){
        $office->assignRole(Roles::Office->value);
        }
    }
}
