<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehiclesSeeder extends Seeder
{
    public function run()
    {
        DB::table('vehicles')->delete();
        $vehicles = [
            [
                'vehicleBrand' => 'مرسيدس',
                'plate' => 'DXB-001',
                'modelYear' => '2022',
                'model' => 'S-Class',
                'licenseNumber' => 'LN-001',
                'photo' => 'storage\\profile-images\\car\\m.jpg',
                'lastDriver' => null,
                'color' => 'أسود',
                'city' => 'دبي',
                'fleet_car' => true,
                'driverId' => null,// => 1,
                'description' => 'سيارة فاخرة مناسبة لخدمة الفخامة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'بي إم دبليو',
                'plate' => 'DXB-002',
                'modelYear' => '2022',
                'model' => '7 Series',
                'licenseNumber' => 'LN-002',
                'photo' => 'storage/images/service/2.png',
                'lastDriver' => null,
                'color' => 'أبيض',
                'city' => 'دبي',
                'fleet_car' => true,
                'driverId' => null,// => 2,
                'description' => 'سيارة رياضية وفاخرة لخدمة الفخامة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'رولز رويس',
                'plate' => 'DXB-003',
                'modelYear' => '2023',
                'model' => 'Ghost',
                'licenseNumber' => 'LN-003',
                'photo' => 'storage/images/service/3.png',
                'lastDriver' => null,
                'color' => 'فضي',
                'city' => 'دبي',
                'fleet_car' => true,
                'driverId' => null,// => 3,
                'description' => 'أفخم السيارات لخدمة الفخامة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'بنتلي',
                'plate' => 'DXB-004',
                'modelYear' => '2023',
                'model' => 'Flying Spur',
                'licenseNumber' => 'LN-004',
                'photo' => 'storage/images/service/4.png',
                'lastDriver' => null,
                'color' => 'أزرق',
                'city' => 'دبي',
                'fleet_car' => true,
                'driverId' => null,// => 4,
                'description' => 'سيارة بريطانية فاخرة لخدمة الفخامة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'تسلا',
                'plate' => 'DXB-005',
                'modelYear' => '2023',
                'model' => 'Model S',
                'licenseNumber' => 'LN-005',
                'photo' => 'storage/images/service/5.png',
                'lastDriver' => null,
                'color' => 'أحمر',
                'city' => 'دبي',
                'fleet_car' => false,
                'driverId' => null,// => 5,
                'description' => 'سيارة كهربائية متطورة لخدمة الرحلات الصديقة للبيئة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'تويوتا',
                'plate' => 'DXB-006',
                'modelYear' => '2021',
                'model' => 'Camry',
                'licenseNumber' => 'LN-006',
                'photo' => 'storage/images/service/1.png',
                'lastDriver' => null,
                'color' => 'أبيض',
                'city' => 'أبوظبي',
                'fleet_car' => false,
                'driverId' => null,// => 6,
                'description' => 'سيارة اعتمادية واقتصادية مناسبة لخدمة السفر والتاكسي.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'نيسان',
                'plate' => 'DXB-007',
                'modelYear' => '2021',
                'model' => 'Altima',
                'licenseNumber' => 'LN-007',
                'photo' => 'storage/images/service/2.png',
                'lastDriver' => null,
                'color' => 'أسود',
                'city' => 'أبوظبي',
                'fleet_car' => false,
                'driverId' => null,// => 7,
                'description' => 'سيارة متعددة الاستخدامات لخدمة السفر والتاكسي.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'هيونداي',
                'plate' => 'DXB-008',
                'modelYear' => '2022',
                'model' => 'Elantra',
                'licenseNumber' => 'LN-008',
                'photo' => 'storage/images/service/3.png',
                'lastDriver' => null,
                'color' => 'رمادي',
                'city' => 'دبي',
                'fleet_car' => false,
                'driverId' => null,// => 8,
                'description' => 'سيارة اقتصادية مناسبة للتاكسي والأسطول.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'مرسيدس كومفورت',
                'plate' => 'DXB-009',
                'modelYear' => '2022',
                'model' => 'E-Class',
                'licenseNumber' => 'LN-009',
                'photo' => 'storage/images/service/4.png',
                'lastDriver' => null,
                'color' => 'أسود',
                'city' => 'دبي',
                'fleet_car' => true,
                'driverId' => null,// => 9,
                'description' => 'سيارة مريحة لخدمة الأسطول والرحلات الطويلة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'بي إم دبليو كومفورت',
                'plate' => 'DXB-010',
                'modelYear' => '2022',
                'model' => '5 Series',
                'licenseNumber' => 'LN-010',
                'photo' => 'storage/images/service/5.png',
                'lastDriver' => null,
                'color' => 'أبيض',
                'city' => 'دبي',
                'fleet_car' => true,
                'driverId' => null,// => 10,
                'description' => 'سيارة مريحة وفاخرة لخدمة الأسطول.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'تويوتا هايبرد',
                'plate' => 'DXB-011',
                'modelYear' => '2023',
                'model' => 'Prius',
                'licenseNumber' => 'LN-011',
                'photo' => 'storage/images/service/1.png',
                'lastDriver' => null,
                'color' => 'أخضر',
                'city' => 'دبي',
                'fleet_car' => false,
                'driverId' => null,// => 11,
                'description' => 'سيارة هجينة لخدمة الرحلات الصديقة للبيئة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'نيسان كهربائية',
                'plate' => 'DXB-012',
                'modelYear' => '2023',
                'model' => 'Leaf',
                'licenseNumber' => 'LN-012',
                'photo' => 'storage/images/service/2.png',
                'lastDriver' => null,
                'color' => 'أخضر',
                'city' => 'دبي',
                'fleet_car' => false,
                'driverId' => null,// => 12,
                'description' => 'سيارة كهربائية مناسبة للرحلات الصديقة للبيئة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'هيونداي هايبرد',
                'plate' => 'DXB-013',
                'modelYear' => '2022',
                'model' => 'Ioniq',
                'licenseNumber' => 'LN-013',
                'photo' => 'storage/images/service/3.png',
                'lastDriver' => null,
                'color' => 'أزرق',
                'city' => 'دبي',
                'fleet_car' => false,
                'driverId' => null,// => 13,
                'description' => 'سيارة هجينة للتاكسي والأسطول.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'تويوتا بريميوم',
                'plate' => 'DXB-014',
                'modelYear' => '2023',
                'model' => 'Camry Premium',
                'licenseNumber' => 'LN-014',
                'photo' => 'storage/images/service/4.png',
                'lastDriver' => null,
                'color' => 'أبيض',
                'city' => 'أبوظبي',
                'fleet_car' => false,
                'driverId' => null,// => 14,
                'description' => 'سيارة مريحة وفاخرة لخدمة السفر.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'نيسان بريميوم',
                'plate' => 'DXB-015',
                'modelYear' => '2023',
                'model' => 'Altima Premium',
                'licenseNumber' => 'LN-015',
                'photo' => 'storage/images/service/5.png',
                'lastDriver' => null,
                'color' => 'أسود',
                'city' => 'أبوظبي',
                'fleet_car' => false,
                'driverId' => null,// => 15,
                'description' => 'سيارة مميزة لخدمة السفر والأسطول.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'لكزس',
                'plate' => 'DXB-016',
                'modelYear' => '2023',
                'model' => 'LS 500',
                'licenseNumber' => 'LN-016',
                'photo' => 'storage/images/service/1.png',
                'lastDriver' => null,
                'color' => 'أسود',
                'city' => 'دبي',
                'fleet_car' => true,
                'driverId' => null,// => 16,
                'description' => 'سيارة فاخرة من لكزس لخدمة رجال الأعمال.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'أودي',
                'plate' => 'DXB-017',
                'modelYear' => '2023',
                'model' => 'A8',
                'licenseNumber' => 'LN-017',
                'photo' => 'storage/images/service/2.png',
                'lastDriver' => null,
                'color' => 'رمادي',
                'city' => 'دبي',
                'fleet_car' => true,
                'driverId' => null,// => 17,
                'description' => 'سيارة ألمانية فاخرة وفسيحة.',
                'seatsCount' => 4,
            ],
            [
                'vehicleBrand' => 'كاديلاك',
                'plate' => 'DXB-018',
                'modelYear' => '2023',
                'model' => 'Escalade',
                'licenseNumber' => 'LN-018',
                'photo' => 'storage/images/service/3.png',
                'lastDriver' => null,
                'color' => 'أبيض',
                'city' => 'أبوظبي',
                'fleet_car' => true,
                'driverId' => null,// => 18,
                'description' => 'سيارة SUV فاخرة وواسعة.',
                'seatsCount' => 7,
            ],
            [
                'vehicleBrand' => 'جي إم سي',
                'plate' => 'DXB-019',
                'modelYear' => '2022',
                'model' => 'Yukon',
                'licenseNumber' => 'LN-019',
                'photo' => 'storage/images/service/4.png',
                'lastDriver' => null,
                'color' => 'أسود',
                'city' => 'أبوظبي',
                'fleet_car' => false,
                'driverId' => null,// => 19,
                'description' => 'سيارة SUV قوية مناسبة للرحلات العائلية.',
                'seatsCount' => 7,
            ],
            [
                'vehicleBrand' => 'فورد',
                'plate' => 'DXB-020',
                'modelYear' => '2021',
                'model' => 'Explorer',
                'licenseNumber' => 'LN-020',
                'photo' => 'storage/images/service/5.png',
                'lastDriver' => null,
                'color' => 'أزرق',
                'city' => 'دبي',
                'fleet_car' => false,
                'driverId' => null,// => 20,
                'description' => 'سيارة SUV عملية للرحلات الطويلة.',
                'seatsCount' => 7,
            ],
            [
                'vehicleBrand' => 'شيفروليه',
                'plate' => 'DXB-021',
                'modelYear' => '2022',
                'model' => 'Tahoe',
                'licenseNumber' => 'LN-021',
                'photo' => 'storage/images/service/1.png',
                'lastDriver' => null,
                'color' => 'فضي',
                'city' => 'دبي',
                'fleet_car' => false,
                'driverId' => null,// => 21,
                'description' => 'سيارة SUV مريحة وواسعة.',
                'seatsCount' => 7,
            ],
            [
                'vehicleBrand' => 'ميتسوبيشي',
                'plate' => 'DXB-022',
                'modelYear' => '2022',
                'model' => 'Pajero',
                'licenseNumber' => 'LN-022',
                'photo' => 'storage\\profile-images\\car\\mm.jpg',
                'lastDriver' => null,
                'color' => 'أبيض',
                'city' => 'أبوظبي',
                'fleet_car' => false,
                'driverId' => null,// => 22,
                'description' => 'سيارة دفع رباعي متعددة الاستخدامات.',
                'seatsCount' => 7,
            ],
            [
                'vehicleBrand' => 'كيا',
                'plate' => 'DXB-023',
                'modelYear' => '2023',
                'model' => 'Carnival',
                'licenseNumber' => 'LN-023',
                'photo' => 'storage\\profile-images\\car\\kia.jpg',
                'lastDriver' => null,
                'color' => 'أسود',
                'city' => 'دبي',
                'fleet_car' => false,
                'driverId' => null,// => 23,
                'description' => 'ميني فان عائلية واسعة ومريحة.',
                'seatsCount' => 7,
            ],
            [
                'vehicleBrand' => 'هوندا',
                'plate' => 'DXB-024',
                'modelYear' => '2023',
                'model' => 'Odyssey',
                'licenseNumber' => 'LN-024',
                'photo' => 'storage\\profile-images\\car\\Honda.jpg',
                'lastDriver' => null,
                'color' => 'أبيض',
                'city' => 'أبوظبي',
                'fleet_car' => false,
                'driverId' => null,// => 24,
                'description' => 'ميني فان مريحة ومناسبة للعائلات.',
                'seatsCount' => 7,
            ],
        ];
        
        $id = 1; 
        foreach ($vehicles as &$vehicle) {
            $vehicle['id'] = $id;
            $id++;
        }

        unset($vehicle);
        DB::table('vehicles')->insert($vehicles);
        

    }
}
